# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b06t6i5yRvtovQ3gqX-1zxPCSJcWEeEd
"""

*ARQUIVO TESTE*
